AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template KYC Form

Globals:
  Function:
    Environment:
      Variables:
        ENV: !Ref env
        APP: !Ref app

Parameters:
  env:
    Type: String
    Description: Deployment Env
  app:
    Type: String
    Description: App Name
Resources:
  MxUserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
      - AttributeName: phone_number
        KeyType: HASH
      AttributeDefinitions:
      - AttributeName: phone_number
        AttributeType: S
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      BillingMode: PAY_PER_REQUEST
  SNSRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: ''
          Effect: Allow
          Principal:
            Service: cognito-idp.amazonaws.com
          Action:
          - sts:AssumeRole
          Condition:
            StringEquals:
              sts:ExternalId: awsfor4e4bd6a6_role_external_id
      Policies:
      - PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - sns:Publish
            Resource: "*"
        PolicyName: sns-policy
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AutoVerifiedAttributes:
      - phone_number
      MfaConfiguration: 'OFF'
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
      Schema:
      - Mutable: true
        Name: email
        Required: true
      - Mutable: true
        Name: name
        Required: true
      - Mutable: true
        Name: phone_number
        Required: true
      - Name: kyc
        AttributeDataType: String
        DeveloperOnlyAttribute: true
        Mutable: true
      SmsAuthenticationMessage: 'Your authentication code is {####}'
      SmsConfiguration:
        ExternalId: awsfor4e4bd6a6_role_external_id
        SnsCallerArn:
          Fn::GetAtt:
          - SNSRole
          - Arn
      SmsVerificationMessage: 'Your verification code is {####}'
      UserAttributeUpdateSettings:
        AttributesRequireVerificationBeforeUpdate:
        - phone_number
      UsernameAttributes: 
        - phone_number
      UsernameConfiguration:
        CaseSensitive: false
      LambdaConfig:
        CreateAuthChallenge: !GetAtt CreateAuthChallenge.Arn
        DefineAuthChallenge: !GetAtt DefineAuthChallenge.Arn
        VerifyAuthChallengeResponse: !GetAtt VerifyAuthChallenge.Arn
  UserPoolClientWeb:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId:
        Ref: UserPool
      RefreshTokenValidity: 1
      TokenValidityUnits:
        RefreshToken: days
    DependsOn:
    - UserPool
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId:
        Ref: UserPool
      GenerateSecret: false
      RefreshTokenValidity: 1
      TokenValidityUnits:
        RefreshToken: days
  IdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      AllowUnauthenticatedIdentities: true
      CognitoIdentityProviders:
      - ClientId:
          Ref: UserPoolClient
        ProviderName:
          Fn::Sub:
          - cognito-idp.${region}.amazonaws.com/${client}
          - region:
              Ref: AWS::Region
            client:
              Ref: UserPool
      - ClientId:
          Ref: UserPoolClientWeb
        ProviderName:
          Fn::Sub:
          - cognito-idp.${region}.amazonaws.com/${client}
          - region:
              Ref: AWS::Region
            client:
              Ref: UserPool
  AuthRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: ''
          Effect: Allow
          Principal:
            Federated: cognito-identity.amazonaws.com
          Action: sts:AssumeRoleWithWebIdentity
          Condition:
            StringEquals:
              "cognito-identity.amazonaws.com:aud": !Ref IdentityPool
            ForAnyValue:StringLike:
              "cognito-identity.amazonaws.com:amr": "authenticated"
  UnauthRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: ''
          Effect: Allow
          Principal:
            Federated: cognito-identity.amazonaws.com
          Action: sts:AssumeRoleWithWebIdentity
          Condition:
            StringEquals:
              "cognito-identity.amazonaws.com:aud": !Ref IdentityPool
            ForAnyValue:StringLike:
              "cognito-identity.amazonaws.com:amr": "unauthenticated"
  ApiExecutePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: KycApiExectuionPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'execute-api:Invoke'
            Resource: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${KycApi}/*/mexusers/*"
      Roles:
        - !Ref UnauthRole
        - !Ref AuthRole
  IdentityPoolRoleMap:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId:
        Ref: IdentityPool
      Roles:
        unauthenticated: !GetAtt UnauthRole.Arn
        authenticated: !GetAtt AuthRole.Arn
  KycApi:
    Type: AWS::Serverless::Api
    Properties:
        StageName: Prod
        Cors:
          AllowMethods: "'POST, GET'"
          AllowHeaders: "'X-Forwarded-For'"
          AllowOrigin: "'*'"
          MaxAge: "'600'" 
  CreateAuthChallenge:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: lambda/CreateAuthChallenge
      Description: ''
      MemorySize: 128
      Timeout: 25
  CreateAuthChallengePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt CreateAuthChallenge.Arn
      Action: lambda:InvokeFunction
      Principal: cognito-idp.amazonaws.com
      SourceArn: !Sub "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${UserPool}"
  DefineAuthChallenge:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: lambda/DefineAuthChallenge
      Description: ''
      MemorySize: 128
      Timeout: 25
  DefineAuthChallengePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt DefineAuthChallenge.Arn
      Action: lambda:InvokeFunction
      Principal: cognito-idp.amazonaws.com
      SourceArn: !Sub "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${UserPool}"
  VerifyAuthChallenge:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: lambda/VerifyAuthChallenge
      Description: ''
      MemorySize: 128
      Timeout: 25
  VerifyAuthChallengePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt VerifyAuthChallenge.Arn
      Action: lambda:InvokeFunction
      Principal: cognito-idp.amazonaws.com
      SourceArn: !Sub "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${UserPool}"
  KycIdentity:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: lambda/KycIdentity
      Description: ''
      MemorySize: 128
      Timeout: 25
      Environment:
        Variables:
          JUMIO_TOKEN: !Sub "/${env}/${app}/JUMIO_TOKEN"
          JUMIO_USER: !Sub "/${env}/${app}/JUMIO_USER"
      Policies:
        - SSMParameterWithSlashPrefixReadPolicy:
            ParameterName: !Sub "/${env}/${app}/*"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /kycidentity/{proxy+}
            Method: any
            RestApiId: !Ref KycApi
            
  UserAthMex:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: lambda/UserAthMex
      Description: ''
      MemorySize: 128
      Timeout: 25
      Environment:
        Variables:
          TABLE_NAME: !Ref MxUserTable
          TABLE_REGION:  !Ref AWS::Region
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MxUserTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /mexusers/{proxy+}
            Method: any
            RestApiId: !Ref KycApi
            Auth:
              Authorizer: AWS_IAM
  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/GetUser/
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          USER_POOL_ID: !Ref UserPool
      Events:
        CognitoUserPool:
          Type: Api
          Properties:
            Path: /user
            Method: get
            RestApiId: !Ref KycApi
      Policies:
        - Statement:
            - Action:
              - "cognito-sync:*"
              - "cognito-idp:*"
              Effect: Allow
              Resource: !GetAtt UserPool.Arn
  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/CreateUser/
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          USER_POOL_ID: !Ref UserPool
      Events:
        CognitoUserPool:
          Type: Api
          Properties:
            Path: /user
            Method: post
            RestApiId: !Ref KycApi
      Policies:
        - Statement:
            - Action:
                - "cognito-sync:*"
                - "cognito-idp:*"
              Effect: Allow
              Resource: !GetAtt UserPool.Arn
  KyccallbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/KycCallback/
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          USER_POOL_ID: !Ref UserPool
      Events:
        CognitoUserPool:
          Type: Api
          Properties:
            Path: /jumio/callback
            Method: get
            RestApiId: !Ref KycApi
      Policies:
        - Statement:
            - Action:
                - "cognito-sync:*"
                - "cognito-idp:*"
              Effect: Allow
              Resource: !GetAtt UserPool.Arn